"""crear tablas iniciales

Revision ID: ed51f4e3895a
Revises: 
Create Date: 2026-05-06 08:42:48.879546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed51f4e3895a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('granjas',
    sa.Column('nombre', sa.String(length=100), nullable=False, comment="Nombre de la granja (ej: 'La Esperanza')"),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='madura=histórico±5% / crecimiento=curva genética'),
    sa.Column('ubicacion', sa.String(length=200), nullable=True, comment='Dirección o descripción geográfica'),
    sa.Column('contacto', sa.String(length=100), nullable=True, comment='Encargado o contacto principal'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('modulos',
    sa.Column('nombre', sa.String(length=50), nullable=False, comment="Nombre del módulo (ej: '100')"),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('granja_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['granja_id'], ['granjas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('granja_id', sa.String(length=36), nullable=True, comment='Granja a la que pertenece este usuario. NULL = acceso global.'),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['granja_id'], ['granjas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('galpones',
    sa.Column('nombre', sa.String(length=50), nullable=False, comment="Nombre del galpón (ej: '101', '102')"),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('capacidad_aves', sa.Integer(), nullable=True, comment='Capacidad máxima de aves en el galpón'),
    sa.Column('modulo_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_auditoria',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID generado en el servidor al momento de registrar el log'),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False, comment="Nombre de la tabla modificada (ej: 'remision_detalles')"),
    sa.Column('registro_id', sa.String(length=36), nullable=False, comment='UUID del registro afectado'),
    sa.Column('campo', sa.String(length=100), nullable=True, comment='Campo específico modificado (null si es CREATE completo)'),
    sa.Column('accion', sa.String(length=20), nullable=False, comment='CREATE | UPDATE | SYNC | AJUSTE | SOFT_DELETE'),
    sa.Column('valor_anterior', sa.Text(), nullable=True, comment='Valor anterior serializado como JSON'),
    sa.Column('valor_nuevo', sa.Text(), nullable=True, comment='Valor nuevo serializado como JSON'),
    sa.Column('motivo', sa.Text(), nullable=True, comment='Razón del cambio (ingresada por el usuario o generada por el sistema)'),
    sa.Column('ip_origen', sa.String(length=45), nullable=True, comment='IP del cliente. Soporta IPv6 (máx 45 chars).'),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_registro_id'), 'log_auditoria', ['registro_id'], unique=False)
    op.create_index(op.f('ix_log_auditoria_tabla_afectada'), 'log_auditoria', ['tabla_afectada'], unique=False)
    op.create_index(op.f('ix_log_auditoria_timestamp'), 'log_auditoria', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_auditoria_usuario_id'), 'log_auditoria', ['usuario_id'], unique=False)
    op.create_table('remisiones',
    sa.Column('numero_remision', sa.Integer(), nullable=True, comment='Número secuencial asignado al sincronizar con el servidor'),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Fecha de despacho desde la granja'),
    sa.Column('fecha_produccion', sa.Date(), nullable=True, comment='Fecha en que fue puesto el huevo (puede diferir del despacho)'),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('huevo_incubable', sa.Integer(), nullable=False),
    sa.Column('total_sucio', sa.Integer(), nullable=False),
    sa.Column('total_roto', sa.Integer(), nullable=False),
    sa.Column('total_extra', sa.Integer(), nullable=False),
    sa.Column('total_huevos', sa.Integer(), nullable=False),
    sa.Column('cajas', sa.Integer(), nullable=False, comment='= huevo_incubable // 360'),
    sa.Column('cubetas', sa.Integer(), nullable=False, comment='= huevo_incubable // 30'),
    sa.Column('cubetas_sobrantes', sa.Integer(), nullable=False, comment='= (huevo_incubable % 360) // 30'),
    sa.Column('unidades_sueltas', sa.Integer(), nullable=False, comment='= huevo_incubable % 30'),
    sa.Column('despachado_por', sa.String(length=100), nullable=True),
    sa.Column('recibido_por', sa.String(length=100), nullable=True),
    sa.Column('numero_sello', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('sincronizado_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp de última sincronización exitosa con el servidor'),
    sa.Column('granja_id', sa.String(length=36), nullable=False),
    sa.Column('creado_por_id', sa.String(length=36), nullable=True, comment='Operario granja que creó el documento'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['granja_id'], ['granjas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_remision')
    )
    op.create_table('huevos_pendientes',
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('resuelto_en_remision_id', sa.String(length=36), nullable=True),
    sa.Column('remision_id', sa.String(length=36), nullable=False),
    sa.Column('galpon_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['remision_id'], ['remisiones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resuelto_en_remision_id'], ['remisiones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lotes',
    sa.Column('codigo', sa.String(length=50), nullable=False, comment="Código único del lote (ej: 'LOT-2024-101-A')"),
    sa.Column('linea_genetica', sa.String(length=50), nullable=True, comment="Línea genética (ej: 'Ross 308', 'Cobb 500')"),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False, comment='Fecha en que las aves ingresaron al galpón'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de salida o sacrificio del lote'),
    sa.Column('numero_aves_inicial', sa.Integer(), nullable=False, comment='Cantidad de aves al inicio del lote'),
    sa.Column('numero_aves_actual', sa.Integer(), nullable=False, comment='Cantidad de aves vivas actualmente (se actualiza por mortalidad)'),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('curva_genetica_ref', sa.Text(), nullable=True, comment='JSON con curva genética teórica por semana de vida'),
    sa.Column('galpon_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('remision_detalles',
    sa.Column('huevo_incubable', sa.Integer(), nullable=False),
    sa.Column('total_sucio', sa.Integer(), nullable=False),
    sa.Column('total_roto', sa.Integer(), nullable=False),
    sa.Column('huevo_extra', sa.Integer(), nullable=False),
    sa.Column('huevo_real_incubable', sa.Integer(), nullable=True),
    sa.Column('huevo_real_sucio', sa.Integer(), nullable=True),
    sa.Column('huevo_real_roto', sa.Integer(), nullable=True),
    sa.Column('huevo_real_extra', sa.Integer(), nullable=True),
    sa.Column('ajuste_incubable', sa.Integer(), nullable=True),
    sa.Column('ajuste_sucio', sa.Integer(), nullable=True),
    sa.Column('ajuste_roto', sa.Integer(), nullable=True),
    sa.Column('ajuste_extra', sa.Integer(), nullable=True),
    sa.Column('entrada_modo', sa.String(length=20), nullable=False, comment="'directo' = unidades, 'calculadora' = cajas+cubetas+unidades"),
    sa.Column('entrada_cajas', sa.Integer(), nullable=True),
    sa.Column('entrada_cubetas', sa.Integer(), nullable=True),
    sa.Column('entrada_unidades', sa.Integer(), nullable=True),
    sa.Column('validacion_estado', sa.String(length=20), nullable=True, comment='ok / alerta / fuera_rango'),
    sa.Column('validacion_mensaje', sa.Text(), nullable=True, comment='Explicación del resultado de validación'),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('remision_id', sa.String(length=36), nullable=False),
    sa.Column('galpon_id', sa.String(length=36), nullable=False),
    sa.Column('modulo_id', sa.String(length=36), nullable=False),
    sa.Column('lote_id', sa.String(length=36), nullable=True, comment='Lote activo en el galpón al momento del despacho'),
    sa.Column('recibido_por_id', sa.String(length=36), nullable=True, comment='Operario Planta que registró los valores reales'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 generado en el cliente para soporte offline'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Última modificación (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete: False = registro desactivado, nunca eliminado físicamente'),
    sa.ForeignKeyConstraint(['galpon_id'], ['galpones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recibido_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remision_id'], ['remisiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remision_detalles')
    op.drop_table('lotes')
    op.drop_table('huevos_pendientes')
    op.drop_table('remisiones')
    op.drop_index(op.f('ix_log_auditoria_usuario_id'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_timestamp'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_tabla_afectada'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_registro_id'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_table('galpones')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('modulos')
    op.drop_table('granjas')
    # ### end Alembic commands ###
